# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
