# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_candidates', '0003_auto_20161016_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
